export class DataTestIds {
    static USER_NAME = "USER_NAME";
    static PASSWORD = "PASSWORD";
    static EMAIL = "EMAIL";
    static SIGN_IN_BUTTON = "SIGN_IN_BUTTON";
    static SIGN_UP_BUTTON = "SIGN_UP_BUTTON";

    static PERSON_BUTTON = "PERSON_BUTTON";
    static PROJECT_BUTTON = "PROJECT_BUTTON";

    static LOAD_PERSONS = "LOAD_PERSONS";
    static PERSON_LIST = "PERSON_LIST";
    static PROGRESS_INDICATOR = "PROGRESS_INDICATOR";
    static ADD_PERSON = "ADD_PERSON";

    static CREATE_PERSON_WRAPPER = "CREATE_PERSON_WRAPPER";
    static PERSON_NAME = "PERSON_NAME";
    static PERSON_COUNTRY = "PERSON_COUNTRY";
    static PROJECT_MENU = "PROJECT_MENU";
    static PROJECT_CHECKBOX = "PROJECT_CHECKBOX";
    static ADD_PERSON_BUTTON = "ADD_PERSON_BUTTON";

    static LOAD_PROJECTS = "LOAD_PROJECTS";
    static PROJECT_LIST = "PROJECT_LIST";
    static ADD_PROJECT = "ADD_PROJECT";

    static CREATE_PROJECT_WRAPPER = "CREATE_PROJECT_WRAPPER";
}
